version: '3'

services:
  jupyter-notebook:
    image: jupyter/scipy-notebook
    volumes:
      - ${WORKING_DIR}:/home/jovyan/work/working
      - ${DATASET_DIR}:/home/jovyan/work/datasets
    ports:
      - ${PORT}:8888
    environment:
      - JUPYTER_TOKEN=${PASSWORD}
    container_name: jupyter-notebook